server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    data-username: root
    data-password: admin
    hikari:
      jdbc-url: jdbc:mysql://localhost
